### ISSUE TITLE
client-ui building problem

### ISSUE THREAD

**Issue by LazyDareDevil** [HronoSF/DSS_2020#6]
DSS_2020/vk-crawler/angular-ui-client/Dockerfile
DSS_2020/vk-crawler/angular-ui-admin/Dockerfile

While building this dockerfiles I got problem, shown on the screenshot.
![Screenshot](https://user-images.githubusercontent.com/32837518/100772246-6bf0db00-3410-11eb-9c9b-5b4bca5e2a1e.png)

I think, problem came from not existing ./node_modules/.bin/protoc-gen-ts folder for protoc --plugin (from reference it should be executable, but it not even exists in node image at all).

**Comment by LazyDareDevil** [comment]
To fix this problem, replace '&' with '&&' in 5th line in these Dockerfiles.

**Comment by HronoSF** [comment]
@LazyDareDevil, can you contact me in vk?
